import Foundation
import Testing
@testable import OracleOS

// MARK: - ToolCommandFamily Tests

@Suite("ToolCommandFamily")
struct ToolCommandFamilyTests {

    @Test("Read-only families do not mutate world")
    func readOnlyFamiliesDoNotMutate() {
        #expect(ToolCommandFamily.capture.mutatesWorld == false)
        #expect(ToolCommandFamily.graphInspect.mutatesWorld == false)
        #expect(ToolCommandFamily.memoryInspect.mutatesWorld == false)
    }

    @Test("Action families mutate world")
    func actionFamiliesMutateWorld() {
        #expect(ToolCommandFamily.app.mutatesWorld == true)
        #expect(ToolCommandFamily.click.mutatesWorld == true)
        #expect(ToolCommandFamily.type.mutatesWorld == true)
        #expect(ToolCommandFamily.shell.mutatesWorld == true)
        #expect(ToolCommandFamily.hotkey.mutatesWorld == true)
    }

    @Test("All cases are accessible via CaseIterable")
    func allCasesAccessible() {
        #expect(ToolCommandFamily.allCases.isEmpty == false)
        #expect(ToolCommandFamily.allCases.contains(.app))
        #expect(ToolCommandFamily.allCases.contains(.capture))
    }

    @Test("graphInspect rawValue is graph_inspect")
    func graphInspectRawValue() {
        #expect(ToolCommandFamily.graphInspect.rawValue == "graph_inspect")
    }

    @Test("memoryInspect rawValue is memory_inspect")
    func memoryInspectRawValue() {
        #expect(ToolCommandFamily.memoryInspect.rawValue == "memory_inspect")
    }
}

// MARK: - ToolCommandSpec Tests

@Suite("ToolCommandSpec")
struct ToolCommandSpecTests {

    @Test("ID auto-generated as family:name when not provided")
    func idAutoGeneratedFromFamilyAndName() {
        let spec = ToolCommandSpec(family: .click, name: "semantic_click")
        #expect(spec.id == "click:semantic_click")
    }

    @Test("Explicit ID is preserved")
    func explicitIDPreserved() {
        let spec = ToolCommandSpec(id: "custom-id", family: .app, name: "launch")
        #expect(spec.id == "custom-id")
    }

    @Test("Family and name are stored correctly")
    func familyAndNameStored() {
        let spec = ToolCommandSpec(family: .type, name: "semantic_type")
        #expect(spec.family == .type)
        #expect(spec.name == "semantic_type")
    }

    @Test("Arguments default to empty dictionary")
    func defaultArgumentsEmpty() {
        let spec = ToolCommandSpec(family: .capture, name: "snapshot")
        #expect(spec.arguments.isEmpty)
    }

    @Test("Provided arguments are stored")
    func providedArgumentsStored() {
        let spec = ToolCommandSpec(family: .app, name: "launch", arguments: ["app": "Safari"])
        #expect(spec.arguments["app"] == "Safari")
    }

    @Test("Specs with same family/name and no explicit ID produce same auto-ID")
    func sameAutoIDForSameFamilyName() {
        let a = ToolCommandSpec(family: .window, name: "focus")
        let b = ToolCommandSpec(family: .window, name: "focus")
        #expect(a.id == b.id)
    }
}

// MARK: - ToolCommandRegistry Tests

@Suite("ToolCommandRegistry")
struct ToolCommandRegistryTests {

    @Test("defaultCommands returns non-empty list")
    func defaultCommandsNonEmpty() {
        let registry = ToolCommandRegistry()
        #expect(registry.defaultCommands().isEmpty == false)
    }

    @Test("defaultCommands includes app launch command")
    func defaultCommandsIncludesAppLaunch() {
        let commands = ToolCommandRegistry().defaultCommands()
        let found = commands.first { $0.family == .app && $0.name == "launch" }
        #expect(found != nil)
    }

    @Test("defaultCommands includes semantic_click")
    func defaultCommandsIncludesSemanticClick() {
        let commands = ToolCommandRegistry().defaultCommands()
        let found = commands.first { $0.family == .click && $0.name == "semantic_click" }
        #expect(found != nil)
    }

    @Test("defaultCommands includes snapshot capture")
    func defaultCommandsIncludesSnapshot() {
        let commands = ToolCommandRegistry().defaultCommands()
        let found = commands.first { $0.family == .capture && $0.name == "snapshot" }
        #expect(found != nil)
    }

    @Test("defaultCommands includes graph inspect")
    func defaultCommandsIncludesGraphInspect() {
        let commands = ToolCommandRegistry().defaultCommands()
        let found = commands.first { $0.family == .graphInspect }
        #expect(found != nil)
    }

    @Test("defaultCommands includes memory inspect")
    func defaultCommandsIncludesMemoryInspect() {
        let commands = ToolCommandRegistry().defaultCommands()
        let found = commands.first { $0.family == .memoryInspect }
        #expect(found != nil)
    }
}

// MARK: - ToolSchemas Tests

@Suite("ToolSchemas")
struct ToolSchemasTests {

    @Test("Schema for app launch has required 'app' argument")
    func schemaForAppLaunch() {
        let spec = ToolCommandSpec(family: .app, name: "launch")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.requiredArguments.contains("app"))
        #expect(schema.description.isEmpty == false)
    }

    @Test("Schema for window focus has required 'app' argument")
    func schemaForWindowFocus() {
        let spec = ToolCommandSpec(family: .window, name: "focus")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.requiredArguments.contains("app"))
    }

    @Test("Schema for semantic_click has required 'query' argument")
    func schemaForSemanticClick() {
        let spec = ToolCommandSpec(family: .click, name: "semantic_click")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.requiredArguments.contains("query"))
    }

    @Test("Schema for semantic_type requires query and text")
    func schemaForSemanticType() {
        let spec = ToolCommandSpec(family: .type, name: "semantic_type")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.requiredArguments.contains("query"))
        #expect(schema.requiredArguments.contains("text"))
    }

    @Test("Schema for snapshot has no required arguments")
    func schemaForSnapshot() {
        let spec = ToolCommandSpec(family: .capture, name: "snapshot")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.requiredArguments.isEmpty)
    }

    @Test("Schema ID matches the spec ID")
    func schemaIDMatchesSpecID() {
        let spec = ToolCommandSpec(family: .app, name: "launch")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.id == spec.id)
    }

    @Test("Unknown command returns default schema with no required arguments")
    func unknownCommandDefaultSchema() {
        let spec = ToolCommandSpec(family: .menu, name: "select")
        let schema = ToolSchemas.schema(for: spec)
        #expect(schema.id == spec.id)
    }

    @Test("ToolSchema is equatable by content")
    func toolSchemaEquality() {
        let a = ToolSchema(id: "x", description: "desc", requiredArguments: ["app"])
        let b = ToolSchema(id: "x", description: "desc", requiredArguments: ["app"])
        #expect(a == b)
    }
}
